language: ruby
cache: bundler
rvm:
  - 2.2.5
git:
  submodules: false
env:
  global:
    - RACK_ENV=test
services:
  - rabbitmq
notifications:
  email:
    recipients:
      - wordman05@gmail.com
    on_success: change
    on_failure: always
branches:
  only:
    - master
install:
  - bundle install
script:
  - ./scripts/setupdb.sh
#  - ruby ./backend/main.rb &
  - rake test --trace
deploy:
  provider: heroku
  api_key: "9951e24c-b489-48fe-8a60-b325e8d850dd"
  app: banbot
  run: "rake db:migrate --trace"